### PR TITLE
 remove CPU throllting and enhance pod crash alert

### PR DESCRIPTION
**Pull request by zjj2wry**
**How to categorize this PR?**

/area TODO
/kind TODO
/priority normal

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

### CODE REVIEW

**Comment by tennix** [comment]
Can you add some context why removing CPU throtling alerts?

**Comment by zjj2wry** [comment]
> Can you add some context why removing CPU throtling alerts?

the upstream already update alert level to info. on the other hand, we will set a smaller limit for some unimportant applications. this will cause alerts, but we should not pay attention to it. I hope we can found some important app high latency or slow task execution, then we query CPUThrotling metrics for this application. Decide if need to set a larger limit

**Comment by zjj2wry** [comment]
sometimes CPUThrollting is an expected result because we don't want some applications to use more CPU.

**Review by tennix — APPROVED** [review]
LGTM

**Review by aylei — APPROVED** [review]
lgtm

**Pull request merged**
